### ISSUE TITLE
JOSS Review--Documentation

### ISSUE THREAD

**Issue by yuxuanzhuang** [moldyn/msmhelper#26]
This is part of the review process for https://github.com/openjournals/joss-reviews/issues/5339

There's a few links broken in the github page

- [https://github.com/moldyn/msmhelper#usage](https://github.com/moldyn/msmhelper#usage)
    - [x] linking issue with API
    - [x] reference issue with **following section**
- [https://github.com/moldyn/msmhelper#hummer-szabo-projection](https://github.com/moldyn/msmhelper#hummer-szabo-projection)
    - [x] linking issue with **tutorial**
- [https://moldyn.github.io/msmhelper/benchmark/](https://moldyn.github.io/msmhelper/benchmark/)
    - [x] Download doesn’t work
   
**Updated May 3**
- [https://moldyn.github.io/msmhelper/tutorials/msm/](https://moldyn.github.io/msmhelper/tutorials/msm/)
    - [x] where λ i is the i -th eigenvalue.
        - of what?
- [https://moldyn.github.io/msmhelper/tutorials/timescales/](https://moldyn.github.io/msmhelper/tutorials/timescales/)
    - [x] raw latex in the webpage
        - e.g. t^\text{wt}
    - [x] unfinished sentence
        - Here we see, that choosing a long lag time
- [https://moldyn.github.io/msmhelper/tutorials/hummerszabo/](https://moldyn.github.io/msmhelper/tutorials/hummerszabo/)
    - [x] raw latex in the webpage
    - [x] typo: neglegtable, evry

**Comment by braniii** [comment]
@yuxuanzhuang, thank you for your review and pointing out these issues. The broken links should be fixed now by the PR #28

**Comment by yuxuanzhuang** [comment]
Hi! I've added with a few more comments on the documentations

**Comment by braniii** [comment]
@yuxuanzhuang  I've just rechecked the documentation with the latest firefox and chrome version and I do not see any raw latex in the webpage. Is it possible that you are using an ad-blocker or are blocking external fonts?

Here is an example how https://moldyn.github.io/msmhelper/tutorials/timescales/ renders:
![screenshot-2023-05-15 11-57-09](https://github.com/moldyn/msmhelper/assets/28560129/6b403a3a-2b92-4ca6-81a9-38e1cad2dbbc)

**Comment by braniii** [comment]
Thank you for bringing this issue to my attention. For now, I will mark it as resolved. However, if you continue to encounter the same LaTeX error, please don't hesitate to reopen this issue and provide more details about the error and the browser you are using. Thank you again for your feedback and helping me improve the documentation!

**Comment by yuxuanzhuang** [comment]
You are right! It's indeed due to my ad blocker. Thanks for resolving all my comments!
