### ISSUE TITLE
JOSS Review--Performance (WIP)

### ISSUE THREAD

**Issue by yuxuanzhuang** [moldyn/msmhelper#27]
This is part of the review process for https://github.com/openjournals/joss-reviews/issues/5339

Thanks for bringing this wonderful package to the MSM world! I am wondering if you have considered conducting a benchmark comparison between msmhelper and Deeptime (https://deeptime-ml.github.io/latest/index.html). It would be fascinating to see how they compare. However, I understand if this is not a critical aspect of this package review.

**Comment by braniii** [comment]
That is an interesting question. I've added a few benchmarks and surprisingly, deeptime is sometimes significantly faster than Pyemma and almost as fast as msmhelper.

But I guess, one should keep in mind that while msmhelper focuses only on estimating msms, deeptime is a much more versatile package focusing on machine learning approaches.
