### ISSUE TITLE
"Overview" page is not formatting text

### ISSUE THREAD

**Issue by yardasol** [moldyn/msmhelper#46]
First off, I'd like to say this project clearly has a lot of work put into it and deserves more love.

**Describe the bug**
The landing page ("Overview") of the webhosted docpages appear to be formatting incorrectly and just outputting raw, rather than formatted, text:

![Screenshot 2024-06-24 at 11-04-27 Overview - msmhelper](https://github.com/moldyn/msmhelper/assets/45364492/efe6530e-4366-4574-997f-5cb60bb6fd8e)

another example from the bottom of the page
![Screenshot 2024-06-24 at 11-04-46 Overview - msmhelper](https://github.com/moldyn/msmhelper/assets/45364492/c3d4a44c-4c33-46a3-8d67-6ecd3d7831ad)

Thankfully, the restof the website seems to be unaffected

**To Reproduce**
Vist 

**Expected behavior**

**Runtime information:**
 - Browser: Firefox 115.12.0esr (64-bit) on Debian 12

**Comment by braniii** [comment]
Hi @yardasol 
thank you for opening this issue. I've found the error source and (hopefully) fixed the issue.
